version: '3.8'

services:
  mcp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-app
    restart: unless-stopped
    ports:
      - "8080:3002"
    environment:
      - PORT=3002
      - NODE_ENV=production
      - DEBUG=false
      - MASA_API_KEY=M2KYV5QmDwPRAZ91OEKfCfHMTq5HaF8C61qgowSfFlYxI1Hf
      - TOGETHER_API_KEY=RpqsYn9xUEg4sZaXcgp7Gt338qncogambjyFC1rDGFjZCF3l
      - TOGETHER_ENHANCEMENT=TRUE
      - MASA_ENHANCEMENT=TRUE
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  logs: