version: '3.8'

services:
  masa-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: masa-mcp
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - NODE_ENV=production
      - DEBUG=false
      # These will be provided by the .env file
      - MASA_API_KEY=${MASA_API_KEY:-}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY:-}
      - TOGETHER_ENHANCEMENT=${TOGETHER_ENHANCEMENT:-FALSE}
      - MASA_ENHANCEMENT=${MASA_ENHANCEMENT:-FALSE}
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network

  playwright-mcp:
    build:
      context: ./playwright-mcp
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    container_name: playwright-mcp
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DOCKER_CONTAINER=true
      - SCRAPE_TIMEOUT=20000
      - BROWSER_TIMEOUT=60000
      # Pass API keys to the Playwright service
      - MASA_API_KEY=${MASA_API_KEY:-}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY:-}
    volumes:
      - ./playwright-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mcp-network
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'

networks:
  mcp-network:
    driver: bridge

volumes:
  masa-mcp-logs:
  playwright-mcp-logs: 